### PR TITLE
Set up appveyor

### PR DESCRIPTION
**Pull request by johnmhoran**

### CODE REVIEW

**Comment by develar** [comment]
We recommend to add tokens via UI.

**Comment by iffy** [comment]
Thank you for submitting this, but since this repo is just to help people get the most basic updating app going, I'm not going to merge this in as is.

But if this repo doesn't work as-is for Windows, I'd like to fix that.

**Comment by johnmhoran** [comment]
@iffy  @develar  My apologies: the error was mine.  I'm experimenting with using `electron-builder` and the auto-update process targeting the Windows platform.  I'd intended to submit a PR to my forked repo, but inadvertently selected the base-fork `master` rather than my own repo's `master`.  To avoid this going forward, I think I'll create a new non-forked project.  Thanks very much for creating this project!

Shall I close my PR?

**Comment by iffy** [comment]
@johnmhoran no worries!  But please, if it's broken on Windows, don't hesitate to submit and Issue or a PR.

**Comment by johnmhoran** [comment]
Thank you @iffy -- will do.

**Pull request closed without merging**
